# Generated by Django 5.1.4 on 2024-12-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avatar',
            field=models.ImageField(null=True, upload_to='upload/%Y/%m'),
        ),
    ]
