# Generated by Django 5.1.2 on 2024-12-11 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_restaurant_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
