# Generated by Django 5.1.2 on 2024-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_maincategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
