# Generated by Django 5.1.2 on 2024-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_maincategory_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='avatar',
            new_name='image',
        ),
    ]
